"""update_users_citext_uuid_index

Revision ID: 74f6809e3b4a
Revises: 1e3badc4e2df
Create Date: 2026-08-29 22:22:53.144179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74f6809e3b4a'
down_revision: Union[str, Sequence[str], None] = '1e3badc4e2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Manually injected: Enable the CITEXT extension before altering the column
    op.execute("CREATE EXTENSION IF NOT EXISTS citext;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_users_artist_status'), 'users', ['artist_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_artist_status'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=postgresql.CITEXT(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###